# Generated by Django 2.0.2 on 2018-05-10 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ascent', models.DateField()),
                ('style', models.CharField(max_length=2)),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ['-date_ascent'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crag', models.CharField(max_length=30)),
                ('sector', models.CharField(blank=True, max_length=30)),
                ('grade', models.CharField(max_length=3)),
                ('user', models.ManyToManyField(through='ranking.Ascent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ascent',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Route'),
        ),
        migrations.AddField(
            model_name='ascent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
