# Generated by Django 2.0.2 on 2018-06-30 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ascent',
            options={'ordering': ['-points', '-date_ascent']},
        ),
        migrations.AlterField(
            model_name='ascent',
            name='style',
            field=models.CharField(choices=[('fl', 'fl'), ('rp', 'rp'), ('os', 'os')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ascent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ascents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(choices=[('6a', '6a'), ('6a+', '6a+'), ('6b', '6b'), ('6b+', '6b+'), ('6c', '6c'), ('6c+', '6c+'), ('7a', '7a'), ('7a+', '7a+'), ('7b', '7b'), ('7b+', '7b+'), ('7c', '7c'), ('7c+', '7c+'), ('8a', '8a'), ('8a+', '8a+'), ('8b', '8b'), ('8b+', '8b+'), ('8c', '8c'), ('8c+', '8c+'), ('9a', '9a'), ('9a+', '9a+'), ('9b', '9b'), ('9b+', '9b+')], max_length=3),
        ),
    ]
