# Generated by Django 2.0.2 on 2018-06-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20180630_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ascent',
            name='route',
        ),
        migrations.RemoveField(
            model_name='ascent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ascent',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
